### ISSUE TITLE
Allow multiple deploy.xml files to deploy independently [enhancement]

### ISSUE THREAD

**Issue by dbaghdanov** [christopherwxyz/NetSuiteSDF#13]
Allow for multiple deployment files, perhaps one for each feature being worked on.  `featureX.deploy.xml` and `featureY.deploy.xml`.  

When a user deploys featureX, those related files and objects are zipped and sdfcli will deploy that zipped project.

**Comment by christopherwxyz** [comment]
Interesting. So, you mean for featureX.deploy.xml to deploy as deploy.xml on user select/dropdown?

**Comment by JonnyBoy333** [comment]
This should be covered by this PR https://github.com/christopherwxyz/NetSuiteSDF/pull/45
