### ISSUE TITLE
Add Matching JavaScript When Adding TypeScript To Deploy XML Functionality No Longer Working

### ISSUE THREAD

**Issue by nathanfiedler-bkdv** [christopherwxyz/NetSuiteSDF#50]
Hey! Great to see your latest 2020.2 updates!

It appears that this feature is now no longer working. Looking through your latest changes, I think this may be the cause, although I haven't had a chance to check in my fork yet...

In **netsuite-sdf.ts**, lines 603-608 (in the getFiles function) this:

```
          await Promise.all(
            subdirs.map(async (subdir) => {
              const res = path.resolve(dir, subdir);
              return (await fs.stat(res)).isDirectory() ? getFiles(res) : res;
            })
          );
```

should be updated to this (the variable assignment is missing):

```
          const files = await Promise.all(
            subdirs.map(async (subdir) => {
              const res = path.resolve(dir, subdir);
              return (await fs.stat(res)).isDirectory() ? getFiles(res) : res;
            })
          );
```

Let me know what you think!

**Comment by nathanfiedler-bkdv** [comment]
Just tested and confirmed that this is all that's needed to get it working again.

**Comment by christopherwxyz** [comment]
@nathanfiedler-bkdv Pushed.

`files` was used in the upper scope, so I used a short variable instead. Let me know if this doesn't solve your issue.
