### ISSUE TITLE
SDF: Import Files - invalid file cabinet path(s) when folder name contains white spaces

### ISSUE THREAD

**Issue by jpetri90** [christopherwxyz/NetSuiteSDF#52]
Hi! 

First of all, I love your extension and it caused me to move away from Eclipse as my standard NetSuite IDE.
I noticed something the other day. I was trying to import a file with a path such as this: /SuiteScripts/FolderName/Folder Name Two/script.js
This throws the following error: The file cabinet path(s) "Name, Two/script.js" are invalid. The file cabinet path must start with either of the following: "/SuiteScripts,/Templates/E-mail Templates,/Templates/Marketing Templates,/Web Site Hosting Files".
Changing "Folder Name Two" to FolderNameTwo resolves the issue.
Thanks for taking a look and let me know if I can provide further details, I am using extension version v2020.2.6.

VS Code about:
Version: 1.49.3 (user setup)
Commit: 2af051012b66169dde0c4dfae3f5ef48f787ff69
Date: 2020-10-02T17:57:01.595Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by christopherwxyz** [comment]
Hey @jpetri90! 

Yeah, it's a tough draw. Whitespaces in previous sdfcli versions caused me headaches when passing those values to the parameters in the CLI, so I adopted a `no whitespace folder` policy to resolve this issue. However, it may now accept them. I'll check it out and see if I can resolve it for you.
